-- Ephemeral SQLx schema for CI and local metadata generation only.
--
-- This file intentionally does not replace or run production migrations. It
-- represents the current canonical server data model. Run it only against a
-- disposable database.

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    picture TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_preferences (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_templates (
    id UUID PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    is_official BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_logs (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_id UUID REFERENCES meal_templates(id) ON DELETE SET NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    nutrition_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    consumed_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE INDEX idx_user_preferences_sync ON user_preferences (id, updated_at);
CREATE INDEX idx_meal_templates_sync ON meal_templates (user_id, updated_at, id);
CREATE INDEX idx_meal_templates_official ON meal_templates (is_official, deleted_at);
CREATE INDEX idx_meal_logs_sync ON meal_logs (user_id, updated_at, id);
CREATE INDEX idx_meal_logs_daily
    ON meal_logs (user_id, consumed_at) WHERE deleted_at IS NULL;

-- API integration tests use this controlled identity and never need a
-- production account.
INSERT INTO users (id, email) VALUES (1, 'sqlx-ci@example.invalid');
SELECT setval(pg_get_serial_sequence('users', 'id'), 1, true);
