-- Ephemeral SQLx schema for CI and local metadata generation only.
--
-- This file intentionally does not replace or run production migrations. It
-- represents the current server data model, including the legacy food and
-- meal tables still used by compile-time SQLx queries. Run it only against a
-- disposable database.

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TYPE serving_unit_type AS ENUM ('weight', 'volume');

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    picture TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE SEQUENCE food_versions_id_seq AS INTEGER;

CREATE TABLE food_versions (
    id INTEGER PRIMARY KEY DEFAULT nextval('food_versions_id_seq'::regclass),
    name VARCHAR(255) NOT NULL,
    calories INTEGER NOT NULL,
    fat NUMERIC NOT NULL,
    proteins NUMERIC NOT NULL,
    carbs NUMERIC NOT NULL,
    saturated_fat NUMERIC,
    monounsaturated_fat NUMERIC,
    polyunsaturated_fat NUMERIC,
    trans_fat NUMERIC,
    fiber NUMERIC,
    sugars NUMERIC,
    sodium INTEGER,
    cholesterol INTEGER,
    version INTEGER NOT NULL,
    previous_version_id INTEGER REFERENCES food_versions(id),
    created_by INTEGER NOT NULL REFERENCES users(id),
    serving_name VARCHAR(255) NOT NULL,
    serving_quantity NUMERIC NOT NULL,
    serving_unit_type serving_unit_type NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER SEQUENCE food_versions_id_seq OWNED BY food_versions.id;

CREATE TABLE foods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by INTEGER NOT NULL REFERENCES users(id),
    current_version_id INTEGER NOT NULL REFERENCES food_versions(id),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE meals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    meal_type VARCHAR(32) NOT NULL,
    eaten_at TIMESTAMP NOT NULL
);

CREATE TABLE meal_foods (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id INTEGER REFERENCES meals(id) ON DELETE CASCADE,
    food_version_id INTEGER REFERENCES food_versions(id),
    serving_name VARCHAR(255) NOT NULL,
    serving_quantity NUMERIC NOT NULL
);

CREATE TABLE user_preferences (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_templates (
    id UUID PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    is_official BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_logs (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_id UUID REFERENCES meal_templates(id) ON DELETE SET NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    nutrition_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    consumed_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

-- API integration tests use this controlled identity and never need a
-- production account.
INSERT INTO users (id, email) VALUES (1, 'sqlx-ci@example.invalid');
SELECT setval(pg_get_serial_sequence('users', 'id'), 1, true);
