-- Ephemeral SQLx schema superseded by the BAL-029 active baseline.
--
-- This file intentionally does not replace or run production migrations. It
-- represents the current canonical server data model. Run it only against a
-- disposable database.

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    picture TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE user_preferences (
    id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    preferences JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_templates (
    id UUID PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    is_official BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_provider VARCHAR(32),
    external_id VARCHAR(128),
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE meal_logs (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_id UUID REFERENCES meal_templates(id) ON DELETE SET NULL,
    name_snapshot VARCHAR(255) NOT NULL,
    nutrition_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_provider VARCHAR(32),
    external_id VARCHAR(128),
    quantity DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    consumed_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT
);

CREATE TABLE weight_logs (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    measured_on DATE NOT NULL,
    weight_grams INTEGER NOT NULL CHECK (
        weight_grams BETWEEN 1000 AND 500000
        AND weight_grams % 100 = 0
    ),
    updated_at BIGINT NOT NULL,
    deleted_at BIGINT,
    PRIMARY KEY (user_id, measured_on)
);

CREATE TABLE food_import_sessions (
    id UUID PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(32) NOT NULL,
    file_fingerprint VARCHAR(128) NOT NULL,
    expected_rows INTEGER NOT NULL CHECK (expected_rows BETWEEN 1 AND 100000),
    templates JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(16) NOT NULL CHECK (status IN ('staged', 'committed', 'cancelled')),
    summary JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    committed_at TIMESTAMPTZ
);

CREATE TABLE food_import_rows (
    session_id UUID NOT NULL REFERENCES food_import_sessions(id) ON DELETE CASCADE,
    row_index INTEGER NOT NULL CHECK (row_index >= 2),
    payload JSONB NOT NULL,
    PRIMARY KEY (session_id, row_index)
);

CREATE INDEX idx_user_preferences_sync ON user_preferences (id, updated_at);
CREATE INDEX idx_meal_templates_sync ON meal_templates (user_id, updated_at, id);
CREATE INDEX idx_meal_templates_official ON meal_templates (is_official, deleted_at);
CREATE INDEX idx_meal_logs_sync ON meal_logs (user_id, updated_at, id);
CREATE INDEX idx_meal_logs_daily
    ON meal_logs (user_id, consumed_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_weight_logs_sync
    ON weight_logs (user_id, updated_at, measured_on);
CREATE UNIQUE INDEX idx_meal_templates_import_identity
    ON meal_templates (user_id, source_provider, external_id)
    WHERE source_provider IS NOT NULL AND external_id IS NOT NULL;
CREATE UNIQUE INDEX idx_meal_logs_import_identity
    ON meal_logs (user_id, source_provider, external_id)
    WHERE source_provider IS NOT NULL AND external_id IS NOT NULL;
CREATE INDEX idx_food_import_sessions_owner
    ON food_import_sessions (user_id, created_at DESC);

-- API integration tests use this controlled identity and never need a
-- production account.
INSERT INTO users (id, email) VALUES (1, 'sqlx-ci@example.invalid');
SELECT setval(pg_get_serial_sequence('users', 'id'), 1, true);
